bill/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<person_id>[0-9]+)/print$', views.printBill, name='print'),
	url(r'^(?P<bill_id>[0-9]+)/pdf_view*', views.myview, name='pdf_view'),
]

sms/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^bill/', include('bill.urls', namespace="bill")),
    url(r'^admin/', admin.site.urls),
]

bill/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Person(models.Model):
	name = models.CharField("Name of Flat Holder", max_length=100)
	email = models.EmailField()
	flat_no = models.CharField("Flat No", max_length=10)
	wing = models.CharField("Wing", max_length=26)
	area = models.CharField("Flat Area", max_length=26)
	mobile = models.IntegerField("Mobile No")

	def __str__(self):
		return self.name

class Bill(models.Model):
	month = models.CharField("Month Of Bill", max_length=20)
	user = models.ForeignKey(Person)
	statement_date = models.DateField()
	due_date = models.DateField()
	sinking_fund = models.IntegerField("Sinking fund")
	repair_and_maintainance = models.IntegerField("Repair and Maintainance")
	water_charges = models.IntegerField("Water Charges")
	electricity_charges = models.IntegerField("Electricity Charges")
	service_charges = models.IntegerField("Service Charges")
	interest = models.IntegerField("Interest rate")
	penalty = models.IntegerField("Penalty")
	adjustments = models.IntegerField("Adjustments")
	unpaid_due = models.IntegerField("Unpaid due")
	payble_amt = models.IntegerField("Total Amount Due")
	total_charges = models.IntegerField("total of charges")

bill/forms.py
from django import forms

class BillForm(forms.Form):
    month = forms.DateField(label='Month')
    statement_date = forms.DateField()
    due_date = forms.DateField()
    sink_fund= forms.DecimalField(label='Sinking Fund')
    repair = forms.DecimalField(label='Repairs & Maintainance')
    water_charges = forms.DecimalField(label='Water Charges')
    electricity_charges = forms.DecimalField(label='Electricity Charges')
    service_charges = forms.DecimalField(label='Service Charges')
    interest = forms.DecimalField(label='Interest')
    penalty = forms.DecimalField(label='Penalty')
    adjustments = forms.DecimalField(label='Adjustments')

bill/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
from .models import Person
from .models import Bill
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import BillForm
from django.views.decorators.cache import cache_page
import StringIO
from cgi import escape
from xhtml2pdf import pisa
from django.http import HttpResponse
from django.template.response import TemplateResponse
from django.views.generic import TemplateView

class IndexView(generic.ListView):
    template_name = 'bill/index.html'
    context_object_name = 'flat_user_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Person.objects.all()

class DetailView(generic.DetailView):
    model = Person
    template_name = 'bill/detail.html'

import cStringIO as StringIO
import ho.pisa as pisa
from django.template.loader import get_template
from django.template import Context
from django.http import HttpResponse
from cgi import escape

def render_to_pdf(template_src, context_dict):
    template = get_template(template_src)
    context = Context(context_dict)
    html = template.render(context)
    result = StringIO.StringIO()
    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return HttpResponse('We had some errors<pre>%s</pre>' % escape(html))

def myview(request, bill_id):
    #Retrieve data or whatever you need
    try:
        billObj = get_object_or_404(Bill, pk=bill_id)
    except:
        return HttpResponse('Bill id is<pre>%s</pre>' % escape(bill_id))
    return render_to_pdf(
            'bill/pdf_view.html',
            {
            'pagesize':'A4',
            'bill': billObj,
            })

def mail_view(request):
    plaintext = get_template('email.txt')
    htmly     = get_template('email.html')

    d = Context({ 'username': username })

    subject, from_email, to = 'hello', 'from@example.com', 'to@example.com'
    text_content = plaintext.render(d)
    html_content = htmly.render(d)
    msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
    msg.attach_alternative(html_content, "text/html")
    msg.send()

def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = BillForm()

    return render(request, 'bill/name.html', {'form': form})

def printBill(request, person_id):
    try:
        flat_user = Person.objects.get(pk=person_id)
    except:
        flat_user= None

    try:
        bill = get_object_or_404(Bill, user=user)
    except:
        bill = None
    if bill == None:
        bill = Bill(user=flat_user)

	bill.due_date = "2015-08-10"
	bill.month = "July"
    bill.statement_date = "2015-08-09"
    bill.sinking_fund = request.POST['sink']
    bill.repair_and_maintainance = request.POST['repair']
    bill.water_charges = request.POST['water_fund']
    bill.electricity_charges = request.POST['electricity_charge']
    bill.service_charges= request.POST['service_charge']
    bill.interest = request.POST['interest']
    bill.penalty = request.POST['penalty']
    bill.adjustments = request.POST['adjustments']
    bill.unpaid_due = 0
    bill.total_charges = request.POST['total']
    bill.payble_amt = request.POST['gross']
    bill.save()

    return render(request, 'bill/print.html', {'bill': bill})

bill/templates/bill/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Home</title>
<center><h1>SURYA VIHAR D & E CO-OP. HSG SOC.LTD.</h1><br>
Registration No.TNA/ABN/HSG/(TC)/20477/2008-2009</small><br>
S.N.43, HISSA No.1 (PART) BEHIND DUBE HOSPITAL, KATRAP<br>
</center>
{% load staticfiles %}

<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'bill/css/style.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'bill/css/layout.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'bill/css/reset.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'bill/css/jqueryCalendar.css' %}" type="text/css" media="all">

<script type="text/javascript" src="{% static 'bill/js/jquery-1.6.2.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'bill/js/cufon-yui.js' %}"></script>
<script type="text/javascript" src="{% static 'bill/js/cufon-replace.js' %}"></script>
<script type="text/javascript" src="{% static 'bill/js/Myriad_Pro_600.font.js' %}"></script>
<script type="text/javascript" src="{% static 'bill/js/jquery-ui-1.8.15.custom.min.js' %}"></script>

<script>
      jQuery(function() {
                      jQuery( "#calendar").datepicker();
                      jQuery( "#calendar1").datepicker();
      });
</script>
</head>
<body id="page1">
<div class="extra">
	<div class="main">
<!-- header -->
		<header>
			<nav>
				<ul id="menu">
					<li><a href="index.html" class="nav1">Home</a></li>
					<li><a href="/admin/bill/person/add/" class="nav2">Add User</a></li>
					<li><a href="/admin/bill/person/" class="nav3">View User</a></li>
					<li><a href="Destinations.html" class="nav4">Records</a></li>
					<li class="end"><a href="Contacts.html" class="nav5">About</a></li>
				</ul>
			</nav>

				<h2>Bill Details</h2>
				<article class="tests">
					<form id="BillDetails" action="{% url 'bill:print' person.id %}" method="post">
						{% csrf_token %}
						<div class="user">
							{% if person %}
							<div class="dateInfo">
									<table cellpadding="12" cellspacing="2" width="100%" bgcolor="white">
									<tr>
										<td align="center" width="10%"><span class="names">Month:: </span></td>
										<td align="center" width="10%">				<select id="month">
																<option value="Jan">Jan</option>
																<option value="Feb">Feb</option>
																<option value="Mar">Mar</option>
																<option value="Apr">Apr</option>
																<option value="May">May</option>
																<option value="Jun">Jun</option>
																<option value="Jul">Jul</option>
																<option value="Aug">Aug</option>
																<option value="Sep">Sep</option>
																<option value="Oct">Oct</option>
																<option value="Nov">Nov</option>
																<option value="Dec">Dec</option>
																</select>
									</td>
									<td align="center" width="20%"><span class="names">Statement Date:</span></td>
									<td align="center" width="20%"> <input type="text" id="calendar" /></td>
									<td align="center" width="20%"><span class="names">Due Date:</span></td>
									<td align="center" width="20%"> <input type="text" id="calendar1" /></td>
									</tr>
									</table>
							</div>
								<table cellpadding="2" cellspacing="2" width="100%" bgcolor="white">
									<tr>
										<td><span class="names">Name of Flat Holder :: </span></td>
										<td>{{ person.name }}</td>
									</tr>
										<td />
									<tr>
										<td><span class="names">Mobile No :: </span></td>
										<td>{{ person.mobile }}</td>
                    <td> Email :: </td>
                    <td>{{ person.email }}</td>
									</tr>
									<tr>
										<td><span class="names">Flat No :: </span></td>
										<td>{{ person.flat_no }}</td>
										<td />
									</tr>
									<tr>
										<td><span class="names">Wing :: </span></td>
										<td>{{ person.wing }}</td>
										<td />
									</tr>
									<tr>
										<td><span class="names">Flat Area :: </span></td>
										<td>{{ person.area }}</td>
										<td />
									</tr>
								</table>
							{% else %}
								<p>No Flat user are available.</p>
							{% endif %}
						</div>

						<div class='test'>
							<div class="content">
								<table cellpadding="2" cellspacing="2" width="100%" bgcolor="black">
									<tr>
										<td bgcolor="#cccccc" align="center"><span class="names">Sr No</span></td>
										<td bgcolor="#cccccc" align="center"><span class="names">Particulars</span></td>
										<td bgcolor="#cccccc" align="center"><span class="names">Amount</span></td>
									</tr>
									<tr>
										<td align="center">1</td>
										<td align="center">Sinking Fund</td>
										<td align="center"><input onblur="sum()" alignment="right" type="text" id="sink" name="sink" value="0" ></td>
									</tr>
									<tr>
										<td align="center">2</td>
										<td align="center">Repairs & Maintainance</td>
										<td align="center"><input onblur="sum()" alignment="right" type="text" id="repair" name="repair" value="0"></td>
									</tr>
									<tr>
										<td align="center">3</td>
										<td align="center">Water Charges</td>
										<td align="center"><input onblur="sum()" alignment="right" type="text" name="water_fund" id="water_fund" value="0" ></td>
									</tr>
									<tr>
										<td align="center">4</td>
										<td align="center">Electricity Charges</td>
										<td align="center"><input onblur="sum()" alignment="right" type="text" id="electricity_charge" name="electricity_charge" value="0" ></td>
									</tr>
									<tr>
										<td align="center">5</td>
										<td align="center">Service Charges</td>
										<td align="center"><input  alignment="right" onblur="sum()" type="text" id="service_charge" name="service_charge" value="0" ></td>
									</tr>
								</table>
								<table cellpadding="2" cellspacing="2" width="100%">
									<tr>
										<td bgcolor="#cccccc" align="center"></td>
										<td bgcolor="#cccccc" align="center"><span class="names">Total</span></td>
										<td bgcolor="#cccccc" align="center"><input style="font-weight: bold;" type="text" id="total" name="total" readonly></td>
									</tr>
									<tr>
										<td align="center"></td>
										<td align="center">Interest</td>
										<td align="center"><input type="text" onblur="total_due()" name="interest" id="interest" bgcolor="red"></td>
									</tr>
									<tr>
										<td align="center"></td>
										<td align="center">Penalty</td>
										<td align="center"><input type="text" onblur="total_due()" name="penalty" id="penalty" bgcolor="red"></td>
									</tr>
									<tr>
										<td align="center"></td>
										<td align="center">Adjustments</td>
										<td align="center"><input type="text" onblur="total_due()" id="adjustments" name="adjustments" bgcolor="red"></td>
									</tr>
									<tr >
										<td bgcolor="#cccccc" align="center"></td>
										<td bgcolor="#cccccc" align="center">Total Due Amount & payable Rs.</td>
										<td bgcolor="#cccccc"align="center"><input style="font-weight: bold;" type="text" id ="gross" name="gross" bgcolor="red"></td>
									</tr>
								</table>
							</div>
						</div>
						<br>
						<input class="cust_button" type="submit" value="print" />
					</form>
				</article>
			</header>
			<div class="img"><img src="" alt=""></div>
		</div>
		<div class="block"></div>
		<div class="block"></div>
	</div>
	<script type="text/javascript">
	 Cufon.now();
	function sum() {
				 var sink = document.getElementById('sink').value;
				 var repair = document.getElementById('repair').value;
				 var water_fund = document.getElementById('water_fund').value;
				 var electricity_charge = document.getElementById('electricity_charge').value;
				 var service_charge = document.getElementById('service_charge').value;
				 if (sink == "")
						 sink = 0;
				 if (repair == "")
						 repair = 0;
				 if (water_fund == "")
						 water_fund = 0;
				 if (electricity_charge == "")
						 electricity_charge = 0;
				 if (service_charge == "")
						 service_charge = 0;

				 var result = parseInt(sink) + parseInt(repair)+ parseInt(water_fund) + parseInt(electricity_charge) + parseInt(service_charge);
				 console.log("Total value")
				 console.log(result)
				 if (!isNaN(result)) {
						 document.getElementById('total').value = result;
				 }
		 }
		 function total_due()
		 {
			 var total = document.getElementById('total').value;
			 console.log("Total Charge")
			 console.log(total)
			 var interest = document.getElementById('interest').value;
			 console.log("interest")
			 console.log(interest)
			 var penalty = document.getElementById('penalty').value;
			 console.log(penalty)
			 var adjustments = document.getElementById('adjustments').value;
			 console.log(adjustments)
			 if (interest == "")
					 interest = 0;
			 if (penalty == "")
					 penalty = 0;
			 if (adjustments == "")
					 adjustments = 0;

			 var amt = 	(parseInt(interest)/100) * parseInt(total)
			 var result = parseInt(total) + parseInt(amt)+ parseInt(penalty) + parseInt(adjustments);
			 console.log(result)
			 if (!isNaN(result)) {
					 document.getElementById('gross').value = result;
			 }

		 }
		 </script>

	</body>
</html>

bill/templates/bill/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Home</title>
<center><h1>SURYA VIHAR D & E CO-OP. HSG SOC.LTD.</h1><br>
Registration No.TNA/ABN/HSG/(TC)/20477/2008-2009</small><br>
S.N.43, HISSA No.1 (PART) BEHIND DUBE HOSPITAL, KATRAP<br>
</center>
{% load staticfiles %}

<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'bill/css/style.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'bill/css/layout.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'bill/css/reset.css' %}" type="text/css" media="all">

<script type="text/javascript" src="{% static 'bill/js/jquery-1.4.2.js' %}" ></script>
<script type="text/javascript" src="{% static 'bill/js/cufon-yui.js' %}"></script>
<script type="text/javascript" src="{% static 'bill/js/cufon-replace.js' %}"></script>
<script type="text/javascript" src="{% static 'bill/js/Myriad_Pro_600.font.js' %}"></script>
</head>
<body id="page1" background="{% static 'bill/images/bg.jpg' %}">
<div class="extra">
	<div class="main">
    <!-- header -->
		<header>
			<nav>
				<ul id="menu">
					<li><a href="index.html" class="nav1">Home</a></li>
					<li><a href="/admin/bill/person/add/" class="nav2">Add User</a></li>
					<li><a href="/admin/bill/person/" class="nav3">View User</a></li>
					<li><a href="Destinations.html" class="nav4">Records</a></li>
					<li class="end"><a href="Contacts.html" class="nav5">About</a></li>
				</ul>
			</nav>
      {% if flat_user_list %}
          <ul>
          {% for flat_user in flat_user_list %}
              <li><a href="/bill/{{ flat_user.id }}/">{{ flat_user.name }}</a></li>
          {% endfor %}
          </ul>
      {% else %}
          <p>No flat User are available.</p>
      {% endif %}
    </header>
  </div>
</div>
</body>
</html>

bill/templates/bill/name.html
<form action="/print/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

bill/templates/bill/pdf_view.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org
/TR/html4/loose.dtd">
<html>
<head>
<title>My Title</title>
<style type="text/css">
@page {
size: {{ pagesize }};
margin: 1cm;
@frame footer {
-pdf-frame-content: footerContent;
bottom: 0cm;
margin-left: 9cm;
margin-right: 9cm;
height: 1cm;
}
}
</style>
</head>
<body>
  <h2>
    <center><h1>SURYA VIHAR D & E CO-OP. HSG SOC.LTD.</h1><br>
    Registration No.TNA/ABN/HSG/(TC)/20477/2008-2009</small><br>
    S.N.43, HISSA No.1 (PART) BEHIND DUBE HOSPITAL, KATRAP<br>
    </center>
  </h2>
    {% if bill %}
      <div class="user" style="width: 100%; margin-left: 1%; margin-bottom: 2%;">
				Month of Bill:: <span class="names">{{ bill.month }}</span>
  			<table cellpadding="2" cellspacing="2" width="100%" bgcolor="white">
						<tr>
							<td> Name of Flat Holder :: </td>
							<td align="left"><span class="names">{{ bill.user.name }}</span></td>
						</tr>
						<tr>
							<td> Mobile No :: </td>
							<td align="left">{{ bill.user.mobile }}</td>
              <td> Email :: </td>
              <td>{{ bill.user.email }}</td>
						</tr>
						<tr>
							<td> Flat No :: </td>
							<td align="left">{{ bill.user.flat_no }}</td>
							<td> Wing :: </td>
							<td align="left">{{ bill.user.wing }}</td>
							<td> Flat Area :: </td>
							<td align="left">{{ bill.user.area }}</td>
						</tr>
				</table>
      </div>
				<table border="1" cellpadding="2" cellspacing="2" width="100%" bgcolor="white">
						<tr>
							<td bgcolor="#cccccc" align="center"><span class="names">Sr No</span></td>
							<td bgcolor="#cccccc" align="center"><span class="names">Particulars</span></td>
							<td bgcolor="#cccccc" align="center"><span class="names">Amount</span></td>
						</tr>
						<tr>
							<td align="center">1</td>
							<td align="center">Sinking Fund</td>
							<td align="center"><i>{{ bill.sinking_fund }}</i></td>
						</tr>
						<tr>
							<td align="center">2</td>
							<td align="center">Repairs & Maintainance</td>
							<td align="center"><i>{{bill.repair_and_maintainance}}</i></td>
						</tr>
						<tr>
							<td align="center">3</td>
							<td align="center">Water Charges</td>
							<td align="center"><i>{{ bill.water_charges }}</i></td>
						</tr>
						<tr>
							<td align="center">4</td>
							<td align="center">Electricity Charges</td>
							<td align="center"><i>{{ bill.electricity_charges }}</i></td>
						</tr>
						<tr>
							<td align="center">5</td>
							<td align="center">Service Charges</td>
							<td align="center"><i>{{ bill.service_charges }}</i></td>
						</tr>
					</table>
					<table border="1" cellpadding="2" cellspacing="2" width="100%">
						<tr>
							<td bgcolor="#cccccc" align="center"></td>
							<td bgcolor="#cccccc" align="center"><span class="names">Total</td>
							<td bgcolor="#cccccc" align="center"><span class="names">{{ bill.total_charges }}</span></td>
						</tr>
						<tr>
							<td align="center"></td>
							<td align="center">Interest</td>
							<td align="center">{{ bill.interest }}</td>
						</tr>
						<tr>
							<td align="center"></td>
							<td align="center">Penalty</td>
							<td align="center">{{ bill.penalty }}</td>
						</tr>
						<tr>
							<td align="center"></td>
							<td align="center">Adjustments</td>
							<td align="center">{{ bill.adjustments }}</td>
						</tr>
						<tr>
							<td align="center"></td>
							<td align="center">Total Due Amount & payable Rs.</td>
							<td align="center"><span class="names">{{ bill.payble_amt }}</span></td>
						</tr>
					</table>
  		{% else %}
  			<p>No Flat user are available.</p>
  		{% endif %}

      <div id="footerContent">
        {%block page_foot%}
        Page <pdf:pagenumber>
      {%endblock%}</body>
</html>

bill/templates/bill/print.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Home</title>
<center><h1>SURYA VIHAR D & E CO-OP. HSG SOC.LTD.</h1><br>
Registration No.TNA/ABN/HSG/(TC)/20477/2008-2009</small><br>
S.N.43, HISSA No.1 (PART) BEHIND DUBE HOSPITAL, KATRAP<br>
</center>
{% load staticfiles %}

<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'bill/css/style.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'bill/css/layout.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'bill/css/reset.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'bill/css/jqueryCalendar.css' %}" type="text/css" media="all">

<script type="text/javascript" src="{% static 'bill/js/jquery-1.6.2.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'bill/js/cufon-yui.js' %}"></script>
<script type="text/javascript" src="{% static 'bill/js/cufon-replace.js' %}"></script>
<script type="text/javascript" src="{% static 'bill/js/Myriad_Pro_600.font.js' %}"></script>
<script type="text/javascript" src="{% static 'bill/js/jquery-ui-1.8.15.custom.min.js' %}"></script>
</head>

<body>
			<h2>Bill Details</h2>
			{% if bill %}
						<form id="BillDetails" action="{% url 'bill:pdf_view' bill.id %}" method="post">
							{% csrf_token %}
								<div class="user" style="width: 100%; margin-left: 1%;">
									Month of Bill:: <span class="names">{{ bill.month }}</span>
									<table cellpadding="2" cellspacing="2" width="40%" bgcolor="white">
											<tr>
												<td> Name of Flat Holder :: </td>
												<td><span class="names">{{ bill.user.name }}</span></td>
											</tr>
											<tr>
												<td> Mobile No :: </td>
												<td>{{ bill.user.mobile }}</td>
												<td> Email :: </td>
												<td>{{ bill.user.email }}</td>
											</tr>
											<tr>
												<td> Flat No :: </td>
												<td>{{ bill.user.flat_no }}</td>
												<td> Wing :: </td>
												<td>{{ bill.user.wing }}</td>
												<td> Flat Area :: </td>
												<td>{{ bill.user.area }}</td>
											</tr>
									</table>
								</div>
									<div class='perticulars'>
										<div class="content">
											<table cellpadding="2" cellspacing="2" width="100%" bgcolor="white">
												<tr>
													<td bgcolor="#cccccc" align="center"><span class="names">Sr No</span></td>
													<td bgcolor="#cccccc" align="center"><span class="names">Particulars</span></td>
													<td bgcolor="#cccccc" align="center"><span class="names">Amount</span></td>
												</tr>
												<tr>
													<td align="center">1</td>
													<td align="center">Sinking Fund</td>
													<td align="center"><i>{{ bill.sinking_fund }}</i></td>
												</tr>
												<tr>
													<td align="center">2</td>
													<td align="center">Repairs & Maintainance</td>
													<td align="center"><i>{{bill.repair_and_maintainance}}</i></td>
												</tr>
												<tr>
													<td align="center">3</td>
													<td align="center">Water Charges</td>
													<td align="center"><i>{{ bill.water_charges }}</i></td>
												</tr>
												<tr>
													<td align="center">4</td>
													<td align="center">Electricity Charges</td>
													<td align="center"><i>{{ bill.electricity_charges }}</i></td>
												</tr>
												<tr>
													<td align="center">5</td>
													<td align="center">Service Charges</td>
													<td align="center"><i>{{ bill.service_charges }}</i></td>
												</tr>
											</table>
											<table cellpadding="2" cellspacing="2" width="100%">
												<tr>
													<td bgcolor="#cccccc" align="center"></td>
													<td bgcolor="#cccccc" align="center"><span class="names">Total</span></td>
													<td bgcolor="#cccccc" align="center"><span class="names">{{ bill.total_charges }}</span></td>
												</tr>
												<tr>
													<td align="center"></td>
													<td align="center">Interest</td>
													<td align="center">{{ bill.interest }}</td>
												</tr>
												<tr>
													<td align="center"></td>
													<td align="center">Penalty</td>
													<td align="center">{{ bill.penalty }}</td>
												</tr>
												<tr>
													<td align="center"></td>
													<td align="center">Adjustments</td>
													<td align="center">{{ bill.adjustments }}</td>
												</tr>
												<tr>
													<td align="center"></td>
													<td align="center"><span class="names">Total Due Amount & payable Rs.</span></td>
													<td align="center"><span class="names">{{ bill.payble_amt }}</span></td>
												</tr>
											</table>
								    </div>
								  </div>
							<input class="cust_button" type="submit" value="PDF" />
						  <button onclick="window.print();">Print And Email</button>
				</form>
		{% else %}
			<p>No Flat user are available.</p>
		{% endif %}

</body>
</html>